### PR TITLE
allow custom snapshot name without automatic date suffix, fixes #1

### LINKED ISSUE #1: Question not an issue
Is there any way to name the snapshot by date like YYYMMDD_HHMM? Thanks.

### PR DESCRIPTION
**Pull request by bahamas10**
```
# ./zfs-snapshot-all -xn "custom_prefix_$(date +%Y%m%d_%H%M)" 
zfs snapshot -r goliath@custom_prefix_20180816_1722 # dry-run: no action taken
zfs snapshot -r zones@custom_prefix_20180816_1722 # dry-run: no action taken
```

### CODE REVIEW

**Comment by 12nick12** [comment]
works perfect. Thank you so much man. You accept donations?

**Comment by 12nick12** [comment]
works perfect like I want with the following command. 
zfs-snapshot-all "$(date +%Y%m%d_%H%M)"

**Comment by bahamas10** [comment]
Thank you for testing! and no donations are necessary, I'm just happy to see people are using my scripts :).  If you absolutely want to I welcome any BTC or LTC (I have yet to actually spend them on anything or use them as a real currency :p)

Bitcoin BTC: 3QnGVTJ7ai2JUjtwxcMZyUwESczqXgckfu
Litecoin LTC: MNzGdZqY15FvCt37js2dEtjkYcKMong8yF

**Comment by 12nick12** [comment]
awesome. Just shot you a couple bucks in LTC.

**Comment by bahamas10** [comment]
thank you!

**Pull request merged**
